# Generated by Django 4.2.6 on 2023-10-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_badiy_bolalar_chettil_diniy_it"),
    ]

    operations = [
        migrations.AddField(
            model_name="chettil",
            name="photo",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="diniy",
            name="photo",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
