# Generated by Django 4.2.6 on 2023-10-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_post_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="it",
            name="photo",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="jahon_adabiyotlar",
            name="photo",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
