# Generated by Django 4.2.6 on 2023-10-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_it_photo_jahon_adabiyotlar_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="badiy",
            name="photo",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="bolalar",
            name="photo",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
