# Generated by Django 4.2.6 on 2023-10-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_badiy_photo_bolalar_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jahon_adabiyotlar",
            name="photo",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="photo",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
